### ISSUE TITLE
Hangout link missing from gcalcli?

### ISSUE THREAD

**Issue by sherzberg** [steveakers/hangout-alert#2]
I just tried to set this up and it seems that the output of `gcalcli` is missing hangout links? Are you still using `hangout-alert`? I'll try to debug why the link is missing if I get a chance.

**Comment by steveakers** [comment]
I am still using hangout-alert. Are you using the latest gcalcli?

Thanks,
Steve

**Comment by sherzberg** [comment]
```bash
$ gcalcli --version
gcalcli v3.2 (Eric Davis, Brian Hartvigsen)
```
Looks like it is the latest version from pypi.

**Comment by steveakers** [comment]
I'm running v3.1, but that's problem not the problem. So when you issue the command in terminal:

```
/usr/local/bin/gcalcli agenda --calendar 'Your Calendar' --tsv
```

Do you see your calendar details just without any hangout links?

**Comment by sherzberg** [comment]
My output looks like this for all entries:

```bash
$ gcalcli agenda --tsv
2015-05-28	09:00	2015-05-28	09:15	Event Name
```

**Comment by steveakers** [comment]
Try this:
```
$ gcalcli agenda --calendar 'Your Calendar' --tsv --details all
```
I was [reading here] (https://github.com/insanum/gcalcli/issues/160) that they added details option to tsv about.

**Comment by sherzberg** [comment]
Victory! Thanks! I also had to change the subprocess call (here is the diff):

```bash
-meetings = %x[/usr/local/bin/gcalcli agenda --calendar 'Your Calendar' --tsv]
+meetings = `/usr/local/bin/gcalcli agenda --tsv --details all`
```

**Comment by steveakers** [comment]
Glad it worked! I'm at the point that I can't live without these hangout reminders. :)
